baseURL = "https://chancesmith.io/"
languageCode = "en-us"
title = "Chance Smith"
ignoreFiles = ["^content/_drafts/", "^content/_ready/"]

[params]
  author = "Chance Smith"
  description = "What if management wasn't about controlling the work, but creating space for it? Exploring leadership that serves engineers instead of managing them."

  [params.social]
    twitter = "chance_smith"
    github = "chancesmith"

[permalinks]
  blog = "/:contentbasename/"

[frontmatter]
  date = [":filename", ":fileModTime"]
  lastmod = [":git", ":fileModTime"]
  publishDate = []
  expiryDate = []

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "github"
